name: Gülşah Film

on:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  update-m3u8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: config
        run: |
          git pull
          git config --global user.email "tvhyrox@gmail.com"
          git config --global user.name "hyroxtvvv"
      - name: Main
        run: |
          pwd
          chmod +x gulsah-film.sh
          ./gulsah-film.sh
      - name: git add
        run: |
          git add -A
          ls -la 
      - name: commit & push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git commit -m "Link updated"
          git push https://$GH_PAT@github.com/hyroxtvvv/hyroxtvapk.git HEAD:main
