name: Gülşah Film

on:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  update-m3u8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Configure Git
        run: |
          git config --global user.email "tvhyrox@gmail.com"
          git config --global user.name "hyroxtvvv"
      - name: Run Script
        run: |
          pwd
          chmod +x gulsah-film.sh
          ./gulsah-film.sh
      - name: Commit and Push changes
        run: |
          git add -A
          git commit -m "Link updated"
          git push
